STRINGS = {
    "en": {
        "tagline": "Smart jeepney income tracker",
        "login_title": "Welcome back",
        "login_sub": "Sign in to continue",
        "email": "Email",
        "password": "Password",
        "sign_in": "Sign In",
        "no_account": "Don't have an account?",
        "register_link": "  Register",
        "register_title": "Create account",
        "register_sub": "Are you a driver or passenger?",
        "full_name": "Full Name",
        "password_hint": "Password (min 6 characters)",
        "create_account": "Create Account",
        "have_account": "Already have an account?",
        "login_link": "  Sign In",
        "driver_btn": "🚐  Driver",
        "passenger_btn": "🧍  Passenger",
        "passenger_label": "PASSENGER",
        "select_stop": "Select your stop",
        "waiting_btn": "📍  I'm Waiting Here!",
        "cancel_btn": "Cancel Waiting",
        "how_title": "How it works",
        "how_body": "Select your stop and tap the button. Nearby drivers will see you are waiting.",
        "logout": "Logout",
        "status_default": "Tap the button to share your location",
        "visible_at": "Visible to drivers near\n",
        "driver_label": "DRIVER",
        "income_lbl": "Income",
        "fuel_lbl": "Fuel",
        "net_lbl": "Net",
        "gas_lbl": "Gas",
        "trips_lbl": "trips today",
        "waiting_section": "Waiting Passengers",
        "no_waiting": "No waiting passengers right now",
        "trip_card_title": "🚐  New Trip",
        "from_lbl": "FROM",
        "to_lbl": "TO",
        "trip_hint": "Select route, then tap Start",
        "start_btn": "Start",
        "complete_btn": "Complete",
        "tips_btn": "💡 Tips",
        "trip_active": "Trip: ",
        "new_day_btn": "🌅 New Day",
        "history_btn": "📅 History",
        "history_title": "📅 Income History",
        "history_sub": "Your daily earnings record",
        "tips_title": "💡 Smart Tips",
        "tips_sub": "Based on passenger demand and fuel price",
    },
    "tl": {
        "tagline": "Smart na tracker ng kita ng jeepney",
        "login_title": "Maligayang pagbabalik",
        "login_sub": "Mag-login para magsimula",
        "email": "Email",
        "password": "Password",
        "sign_in": "Mag-login",
        "no_account": "Wala pang account?",
        "register_link": "  Mag-register",
        "register_title": "Gumawa ng account",
        "register_sub": "Ikaw ba ay driver o pasahero?",
        "full_name": "Buong Pangalan",
        "password_hint": "Password (min 6 na karakter)",
        "create_account": "Gumawa ng Account",
        "have_account": "May account na?",
        "login_link": "  Mag-login",
        "driver_btn": "🚐  Driver",
        "passenger_btn": "🧍  Pasahero",
        "passenger_label": "PASAHERO",
        "select_stop": "Piliin ang iyong stop",
        "waiting_btn": "📍  Nandito Ako!",
        "cancel_btn": "Kanselahin",
        "how_title": "Paano gumagana?",
        "how_body": "Piliin ang stop mo at i-tap ang button. Makikita ka ng mga driver na malapit.",
        "logout": "Mag-logout",
        "status_default": "I-tap ang button para ibahagi ang lokasyon mo",
        "visible_at": "Nakikita ng mga driver malapit sa\n",
        "driver_label": "DRIVER",
        "income_lbl": "Kita",
        "fuel_lbl": "Gasolina",
        "net_lbl": "Net",
        "gas_lbl": "Gas",
        "trips_lbl": "biyahe ngayon",
        "waiting_section": "Mga Naghihintay",
        "no_waiting": "Walang naghihintay ngayon",
        "trip_card_title": "🚐  Bagong Biyahe",
        "from_lbl": "MULA",
        "to_lbl": "PATUNGO",
        "trip_hint": "Piliin ang ruta, tapos i-tap ang Simulan",
        "start_btn": "Simulan",
        "complete_btn": "Tapusin",
        "tips_btn": "💡 Tips",
        "trip_active": "Biyahe: ",
        "new_day_btn": "🌅 Bagong Araw",
        "history_btn": "📅 Kasaysayan",
        "history_title": "📅 Kasaysayan ng Kita",
        "history_sub": "Rekord ng iyong pang-araw-araw na kita",
        "tips_title": "💡 Smart Tips",
        "tips_sub": "Base sa demand ng pasahero at presyo ng gasolina",
    }
}

_current = "en"

def set_lang(code):
    global _current
    _current = code

def get_lang():
    return _current

def t(key):
    return STRINGS.get(_current, STRINGS["en"]).get(key, key)