name: Build Kivy APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show versions
        run: |
          python3 --version
          buildozer --version

      - name: Clean previous build
        run: |
          rm -rf .buildozer
          rm -rf bin

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
